SELECT  [id]
      ,[numero]
      ,[id_pers]
      ,[emision]
      ,[vencimiento]
      ,[manipula]
      ,[id_giro]
      ,[ocupacion]
      ,[estado]
      ,[id_usuario]
      ,[host]
      ,[created_at]
      ,[num_rec]
      ,[qr_code]
      ,[id_funcionario]
      ,[migracion]
      ,[pdf]
      ,[numero_documento]
  FROM [BD_INTRANET].[salud].[s_carnet]
--
  SELECT  [id]
      ,[id_pers]
      ,[numero]
      ,[emision]
      ,[vencimiento]
      ,[id_giro]
      ,[estado]
      ,[id_usuario]
      ,[host]
      ,[created_at]
      ,[num_rec]
      ,[ocupacion]
      ,[id_funcionario]
      ,[migracion]
      ,[pdf]
      ,[numero_documento]
      ,[establecimiento]
  FROM [BD_INTRANET].[salud].[s_certificado]
